# The Legend of Heroes: Trails of Cold Steel IV - Save Unpacker
# (c)2026 Damian Parrino

all: decrypter

decrypter:
	gcc -D _GNU_SOURCE -o trails-cs4-unpacker main.c

clean:
	-rm -f trails-cs4-unpacker
